<?php

use Illuminate\Database\Seeder;

class AlbumsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $albums = [
            [1,1, 'For Those About To Rock We Salute You',8.99,'assets/images/placeholder.gif'],
            [1,1, 'Let There Be Rock',8.99,'assets/images/placeholder.gif'],
            [1,100, 'Greatest Hits',8.99,'assets/images/placeholder.gif'],
            [1,102, 'Misplaced Childhood',8.99,'assets/images/placeholder.gif'],
            [1,105, 'The Best Of Men At Work',8.99,'assets/images/placeholder.gif'],
            [1,110, 'Nevermind',8.99,'assets/images/placeholder.gif'],
            [1,111, 'Compositores',8.99,'assets/images/placeholder.gif'],
            [1,114, 'Bark at the Moon (Remastered)',8.99,'assets/images/placeholder.gif'],
            [1,114, 'Blizzard of Ozz',8.99,'assets/images/placeholder.gif'],
            [1,114, 'Diary of a Madman (Remastered)',8.99,'assets/images/placeholder.gif'],
            [1,114, 'No More Tears (Remastered)',8.99,'assets/images/placeholder.gif'],
            [1,114, 'Speak of the Devil',8.99,'assets/images/placeholder.gif'],
            [1,115, 'Walking Into Clarksdale',8.99,'assets/images/placeholder.gif'],
            [1,117, 'The Beast Live',8.99,'assets/images/placeholder.gif'],
            [1,118, 'Live On Two Legs [Live]',8.99,'assets/images/placeholder.gif'],
            [1,118, 'Riot Act',8.99,'assets/images/placeholder.gif'],
            [1,118, 'Ten',8.99,'assets/images/placeholder.gif'],
            [1,118, 'Vs.',8.99,'assets/images/placeholder.gif'],
            [1,120, 'Dark Side Of The Moon',8.99,'assets/images/placeholder.gif'],
            [1,124, 'New Adventures In Hi-Fi',8.99,'assets/images/placeholder.gif'],
            [1,126, 'Raul Seixas',8.99,'assets/images/placeholder.gif'],
            [1,127, 'By The Way',8.99,'assets/images/placeholder.gif'],
            [1,127, 'Californication',8.99,'assets/images/placeholder.gif'],
            [1,128, 'Retrospective I (1974-1980)',8.99,'assets/images/placeholder.gif'],
            [1,130, 'Maquinarama',8.99,'assets/images/placeholder.gif'],
            [1,130, 'O Samba Poconé',8.99,'assets/images/placeholder.gif'],
            [1,132, 'A-Sides',8.99,'assets/images/placeholder.gif'],
            [1,134, 'Core',8.99,'assets/images/placeholder.gif'],
            [1,136, '[1997] Black Light Syndrome',8.99,'assets/images/placeholder.gif'],
            [1,139, 'Beyond Good And Evil',8.99,'assets/images/placeholder.gif'],
            [1,140, 'The Doors',8.99,'assets/images/placeholder.gif'],
            [1,141, 'The Police Greatest Hits',8.99,'assets/images/placeholder.gif'],
            [1,142, 'Hot Rocks, 1964-1971 (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [1,142, 'No Security',8.99,'assets/images/placeholder.gif'],
            [1,142, 'Voodoo Lounge',8.99,'assets/images/placeholder.gif'],
            [1,144, 'My Generation - The Very Best Of The Who',8.99,'assets/images/placeholder.gif'],
            [1,150, 'Achtung Baby',8.99,'assets/images/placeholder.gif'],
            [1,150, 'B-Sides 1980-1990',8.99,'assets/images/placeholder.gif'],
            [1,150, 'How To Dismantle An Atomic Bomb',8.99,'assets/images/placeholder.gif'],
            [1,150, 'Pop',8.99,'assets/images/placeholder.gif'],
            [1,150, 'Rattle And Hum',8.99,'assets/images/placeholder.gif'],
            [1,150, 'The Best Of 1980-1990',8.99,'assets/images/placeholder.gif'],
            [1,150, 'War',8.99,'assets/images/placeholder.gif'],
            [1,150, 'Zooropa',8.99,'assets/images/placeholder.gif'],
            [1,152, 'Diver Down',8.99,'assets/images/placeholder.gif'],
            [1,152, 'The Best Of Van Halen, Vol. I',8.99,'assets/images/placeholder.gif'],
            [1,152, 'Van Halen III',8.99,'assets/images/placeholder.gif'],
            [1,152, 'Van Halen',8.99,'assets/images/placeholder.gif'],
            [1,153, 'Contraband',8.99,'assets/images/placeholder.gif'],
            [1,157, 'Un-Led-Ed',8.99,'assets/images/placeholder.gif'],
            [1,2, 'Balls to the Wall',8.99,'assets/images/placeholder.gif'],
            [1,2, 'Restless and Wild',8.99,'assets/images/placeholder.gif'],
            [1,200, 'Every Kind of Light',8.99,'assets/images/placeholder.gif'],
            [1,22, 'BBC Sessions [Disc 1] [Live]',8.99,'assets/images/placeholder.gif'],
            [1,22, 'BBC Sessions [Disc 2] [Live]',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Coda',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Houses Of The Holy',8.99,'assets/images/placeholder.gif'],
            [1,22, 'In Through The Out Door',8.99,'assets/images/placeholder.gif'],
            [1,22, 'IV',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Led Zeppelin I',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Led Zeppelin II',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Led Zeppelin III',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Physical Graffiti [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Physical Graffiti [Disc 2]',8.99,'assets/images/placeholder.gif'],
            [1,22, 'Presence',8.99,'assets/images/placeholder.gif'],
            [1,22, 'The Song Remains The Same (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [1,22, 'The Song Remains The Same (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [1,23, 'Bongo Fury',8.99,'assets/images/placeholder.gif'],
            [1,3, 'Big Ones',8.99,'assets/images/placeholder.gif'],
            [1,4, 'Jagged Little Pill',8.99,'assets/images/placeholder.gif'],
            [1,5, 'Facelift',8.99,'assets/images/placeholder.gif'],
            [1,51, 'Greatest Hits I',8.99,'assets/images/placeholder.gif'],
            [1,51, 'Greatest Hits II',8.99,'assets/images/placeholder.gif'],
            [1,51, 'News Of The World',8.99,'assets/images/placeholder.gif'],
            [1,52, 'Greatest Kiss',8.99,'assets/images/placeholder.gif'],
            [1,52, 'Unplugged [Live]',8.99,'assets/images/placeholder.gif'],
            [1,55, 'Into The Light',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Come Taste The Band',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Deep Purple In Rock',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Fireball',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Machine Head',8.99,'assets/images/placeholder.gif'],
            [1,58, 'MK III The Final Concerts [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Purpendicular',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Slaves And Masters',8.99,'assets/images/placeholder.gif'],
            [1,58, 'Stormbringer',8.99,'assets/images/placeholder.gif'],
            [1,58, 'The Battle Rages On',8.99,'assets/images/placeholder.gif'],
            [1,58, 'The Final Concerts (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [1,59, 'Santana - As Years Go By',8.99,'assets/images/placeholder.gif'],
            [1,59, 'Santana Live',8.99,'assets/images/placeholder.gif'],
            [1,59, 'Supernatural',8.99,'assets/images/placeholder.gif'],
            [1,76, 'Chronicle, Vol. 1',8.99,'assets/images/placeholder.gif'],
            [1,76, 'Chronicle, Vol. 2',8.99,'assets/images/placeholder.gif'],
            [1,8, 'Audioslave',8.99,'assets/images/placeholder.gif'],
            [1,82, 'King For A Day Fool For A Lifetime',8.99,'assets/images/placeholder.gif'],
            [1,84, 'In Your Honor [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [1,84, 'In Your Honor [Disc 2]',8.99,'assets/images/placeholder.gif'],
            [1,84, 'The Colour And The Shape',8.99,'assets/images/placeholder.gif'],
            [1,88, 'Appetite for Destruction',8.99,'assets/images/placeholder.gif'],
            [1,88, 'Use Your Illusion I',8.99,'assets/images/placeholder.gif'],
            [1,90, 'A Matter of Life and Death',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Brave New World',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Fear Of The Dark',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Live At Donington 1992 (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Live At Donington 1992 (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Rock In Rio [CD2]',8.99,'assets/images/placeholder.gif'],
            [1,90, 'The Number of The Beast',8.99,'assets/images/placeholder.gif'],
            [1,90, 'The X Factor',8.99,'assets/images/placeholder.gif'],
            [1,90, 'Virtual XI',8.99,'assets/images/placeholder.gif'],
            [1,92, 'Emergency On Planet Earth',8.99,'assets/images/placeholder.gif'],
            [1,94, 'Are You Experienced?',8.99,'assets/images/placeholder.gif'],
            [1,95, 'Surfing with the Alien (Remastered)',8.99,'assets/images/placeholder.gif'],
            [10,203, 'The Best of Beethoven',8.99,'assets/images/placeholder.gif'],
            [10,208, 'Pachelbel: Canon & Gigue',8.99,'assets/images/placeholder.gif'],
            [10,211, 'Bach: Goldberg Variations',8.99,'assets/images/placeholder.gif'],
            [10,212, 'Bach: The Cello Suites',8.99,'assets/images/placeholder.gif'],
            [10,213, 'Handel: The Messiah (Highlights)',8.99,'assets/images/placeholder.gif'],
            [10,217, 'Haydn: Symphonies 99 - 104',8.99,'assets/images/placeholder.gif'],
            [10,219, 'A Soprano Inspired',8.99,'assets/images/placeholder.gif'],
            [10,221, 'Wagner: Favourite Overtures',8.99,'assets/images/placeholder.gif'],
            [10,223, 'Tchaikovsky: The Nutcracker',8.99,'assets/images/placeholder.gif'],
            [10,224, 'The Last Night of the Proms',8.99,'assets/images/placeholder.gif'],
            [10,226, 'Respighi:Pines of Rome',8.99,'assets/images/placeholder.gif'],
            [10,226, 'Strauss: Waltzes',8.99,'assets/images/placeholder.gif'],
            [10,229, 'Carmina Burana',8.99,'assets/images/placeholder.gif'],
            [10,230, 'A Copland Celebration, Vol. I',8.99,'assets/images/placeholder.gif'],
            [10,231, 'Bach: Toccata & Fugue in D Minor',8.99,'assets/images/placeholder.gif'],
            [10,232, 'Prokofiev: Symphony No.1',8.99,'assets/images/placeholder.gif'],
            [10,233, 'Scheherazade',8.99,'assets/images/placeholder.gif'],
            [10,234, 'Bach: The Brandenburg Concertos',8.99,'assets/images/placeholder.gif'],
            [10,236, 'Mascagni: Cavalleria Rusticana',8.99,'assets/images/placeholder.gif'],
            [10,237, 'Sibelius: Finlandia',8.99,'assets/images/placeholder.gif'],
            [10,242, 'Adams, John: The Chairman Dances',8.99,'assets/images/placeholder.gif'],
            [10,245, 'Berlioz: Symphonie Fantastique',8.99,'assets/images/placeholder.gif'],
            [10,245, 'Prokofiev: Romeo & Juliet',8.99,'assets/images/placeholder.gif'],
            [10,247, 'English Renaissance',8.99,'assets/images/placeholder.gif'],
            [10,248, 'Mozart: Symphonies Nos. 40 & 41',8.99,'assets/images/placeholder.gif'],
            [10,250, 'SCRIABIN: Vers la flamme',8.99,'assets/images/placeholder.gif'],
            [10,255, 'Bartok: Violin & Viola Concertos',8.99,'assets/images/placeholder.gif'],
            [10,259, 'South American Getaway',8.99,'assets/images/placeholder.gif'],
            [10,260, 'Górecki: Symphony No. 3',8.99,'assets/images/placeholder.gif'],
            [10,261, 'Purcell: The Fairy Queen',8.99,'assets/images/placeholder.gif'],
            [10,264, 'Weill: The Seven Deadly Sins',8.99,'assets/images/placeholder.gif'],
            [10,266, 'Szymanowski: Piano Works, Vol. 1',8.99,'assets/images/placeholder.gif'],
            [10,267, 'Nielsen: The Six Symphonies',8.99,'assets/images/placeholder.gif'],
            [10,274, 'Mozart: Chamber Music',8.99,'assets/images/placeholder.gif'],
            [2,10, 'The Best Of Billy Cobham',8.99,'assets/images/placeholder.gif'],
            [2,197, 'Quiet Songs',8.99,'assets/images/placeholder.gif'],
            [2,202, 'Worlds',8.99,'assets/images/placeholder.gif'],
            [2,27, 'Quanta Gente Veio ver--Bônus De Carnaval',8.99,'assets/images/placeholder.gif'],
            [2,53, 'Heart of the Night',8.99,'assets/images/placeholder.gif'],
            [2,53, 'Morning Dance',8.99,'assets/images/placeholder.gif'],
            [2,6, 'Warner 25 Anos',8.99,'assets/images/placeholder.gif'],
            [2,68, 'Miles Ahead',8.99,'assets/images/placeholder.gif'],
            [2,68, 'The Essential Miles Davis [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [2,68, 'The Essential Miles Davis [Disc 2]',8.99,'assets/images/placeholder.gif'],
            [2,79, 'Outbreak',8.99,'assets/images/placeholder.gif'],
            [2,89, 'Blue Moods',8.99,'assets/images/placeholder.gif'],
            [3,100, 'Greatest Hits',8.99,'assets/images/placeholder.gif'],
            [3,106, 'Ace Of Spades',8.99,'assets/images/placeholder.gif'],
            [3,109, 'Motley Crue Greatest Hits',8.99,'assets/images/placeholder.gif'],
            [3,11, 'Alcohol Fueled Brewtality Live! [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [3,11, 'Alcohol Fueled Brewtality Live! [Disc 2]',8.99,'assets/images/placeholder.gif'],
            [3,114, 'Tribute',8.99,'assets/images/placeholder.gif'],
            [3,12, 'Black Sabbath Vol. 4 (Remaster)',8.99,'assets/images/placeholder.gif'],
            [3,12, 'Black Sabbath',8.99,'assets/images/placeholder.gif'],
            [3,135, 'Mezmerize',8.99,'assets/images/placeholder.gif'],
            [3,14, 'Chemical Wedding',8.99,'assets/images/placeholder.gif'],
            [3,50, '...And Justice For All',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Black Album',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Garage Inc. (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Garage Inc. (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Load',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Master Of Puppets',8.99,'assets/images/placeholder.gif'],
            [3,50, 'ReLoad',8.99,'assets/images/placeholder.gif'],
            [3,50, 'Ride The Lightning',8.99,'assets/images/placeholder.gif'],
            [3,50, 'St. Anger',8.99,'assets/images/placeholder.gif'],
            [3,7, 'Plays Metallica By Four Cellos',8.99,'assets/images/placeholder.gif'],
            [3,87, 'Faceless',8.99,'assets/images/placeholder.gif'],
            [3,88, 'Use Your Illusion II',8.99,'assets/images/placeholder.gif'],
            [3,90, 'A Real Dead One',8.99,'assets/images/placeholder.gif'],
            [3,90, 'A Real Live One',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Live After Death',8.99,'assets/images/placeholder.gif'],
            [3,90, 'No Prayer For The Dying',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Piece Of Mind',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Powerslave',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Rock In Rio [CD1]',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Rock In Rio [CD2]',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Seventh Son of a Seventh Son',8.99,'assets/images/placeholder.gif'],
            [3,90, 'Somewhere in Time',8.99,'assets/images/placeholder.gif'],
            [3,90, 'The Number of The Beast',8.99,'assets/images/placeholder.gif'],
            [3,98, 'Living After Midnight',8.99,'assets/images/placeholder.gif'],
            [4,196, 'Cake: B-Sides and Rarities',8.99,'assets/images/placeholder.gif'],
            [4,204, 'Temple of the Dog',8.99,'assets/images/placeholder.gif'],
            [4,205, 'Carry On',8.99,'assets/images/placeholder.gif'],
            [4,253, 'Carried to Dust (Bonus Track Version)',8.99,'assets/images/placeholder.gif'],
            [4,8, 'Revelations',8.99,'assets/images/placeholder.gif'],
            [6,133, 'In Step',8.99,'assets/images/placeholder.gif'],
            [6,137, 'Live [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [6,137, 'Live [Disc 2]',8.99,'assets/images/placeholder.gif'],
            [6,81, 'The Cream Of Clapton',8.99,'assets/images/placeholder.gif'],
            [6,81, 'Unplugged',8.99,'assets/images/placeholder.gif'],
            [6,90, 'Iron Maiden',8.99,'assets/images/placeholder.gif'],
            [7,103, 'Barulhinho Bom',8.99,'assets/images/placeholder.gif'],
            [7,112, 'Olodum',8.99,'assets/images/placeholder.gif'],
            [7,113, 'Acústico MTV',8.99,'assets/images/placeholder.gif'],
            [7,113, 'Arquivo II',8.99,'assets/images/placeholder.gif'],
            [7,113, 'Arquivo Os Paralamas Do Sucesso',8.99,'assets/images/placeholder.gif'],
            [7,145, 'Serie Sem Limite (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [7,145, 'Serie Sem Limite (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [7,155, 'Ao Vivo [IMPORT]',8.99,'assets/images/placeholder.gif'],
            [7,16, 'Prenda Minha',8.99,'assets/images/placeholder.gif'],
            [7,16, 'Sozinho Remix Ao Vivo',8.99,'assets/images/placeholder.gif'],
            [7,17, 'Minha Historia',8.99,'assets/images/placeholder.gif'],
            [7,18, 'Afrociberdelia',8.99,'assets/images/placeholder.gif'],
            [7,18, 'Da Lama Ao Caos',8.99,'assets/images/placeholder.gif'],
            [7,20, 'Na Pista',8.99,'assets/images/placeholder.gif'],
            [7,201, 'Duos II',8.99,'assets/images/placeholder.gif'],
            [7,21, 'Sambas De Enredo 2001',8.99,'assets/images/placeholder.gif'],
            [7,21, 'Vozes do MPB',8.99,'assets/images/placeholder.gif'],
            [7,24, 'Chill: Brazil (Disc 1)',8.99,'assets/images/placeholder.gif'],
            [7,27, 'Quanta Gente Veio Ver (Live)',8.99,'assets/images/placeholder.gif'],
            [7,37, 'The Best of Ed Motta',8.99,'assets/images/placeholder.gif'],
            [7,41, 'Elis Regina-Minha História',8.99,'assets/images/placeholder.gif'],
            [7,42, 'Milton Nascimento Ao Vivo',8.99,'assets/images/placeholder.gif'],
            [7,42, 'Minas',8.99,'assets/images/placeholder.gif'],
            [7,46, 'Jorge Ben Jor 25 Anos',8.99,'assets/images/placeholder.gif'],
            [7,56, 'Meus Momentos',8.99,'assets/images/placeholder.gif'],
            [7,6, 'Chill: Brazil (Disc 2)',8.99,'assets/images/placeholder.gif'],
            [7,72, 'Vinicius De Moraes',8.99,'assets/images/placeholder.gif'],
            [7,77, 'Cássia Eller - Sem Limite [Disc 1]',8.99,'assets/images/placeholder.gif'],
            [7,80, 'Djavan Ao Vivo - Vol. 02',8.99,'assets/images/placeholder.gif'],
            [7,80, 'Djavan Ao Vivo - Vol. 1',8.99,'assets/images/placeholder.gif'],
            [7,81, 'Unplugged',8.99,'assets/images/placeholder.gif'],
            [7,83, 'Deixa Entrar',8.99,'assets/images/placeholder.gif'],
            [7,86, 'Roda De Funk',8.99,'assets/images/placeholder.gif'],
            [7,96, 'Jota Quest-1995',8.99,'assets/images/placeholder.gif'],
            [7,99, 'Mais Do Mesmo',8.99,'assets/images/placeholder.gif'],
            [8,100, 'Greatest Hits',8.99,'assets/images/placeholder.gif'],
            [8,151, 'UB40 The Best Of - Volume Two [UK]',8.99,'assets/images/placeholder.gif'],
            [8,19, 'Acústico MTV [Live]',8.99,'assets/images/placeholder.gif'],
            [8,19, 'Cidade Negra - Hits',8.99,'assets/images/placeholder.gif'],
            [9,21, 'Axé Bahia 2001',8.99,'assets/images/placeholder.gif'],
            [9,252, 'Frank',8.99,'assets/images/placeholder.gif'],
            [5,276, 'Le Freak',8.99,'assets/images/placeholder.gif'],
            [5,278, 'MacArthur Park Suite',8.99,'assets/images/placeholder.gif'],
            [5,277, 'Ring My Bell',8.99,'assets/images/placeholder.gif']
        ];
        foreach($albums as $album)
        {
            DB::table('albums')->insert([
                'genreId' => $album[0], 
                'artisteId' => $album[1],
                'titre' => $album[2],
                'prix' => $album[3],
                'albumArtUrl' => $album[4],
                'created_at' => new \DateTime()
            ]);
        }
    }
}
