export var youtubeEmbedUrls = function()
{
  return [
            [
                {titre:"Introduction",url: "https://www.youtube.com/embed/0eWrpsCLMJQ"},
                {titre:"Getting Started",url:"https://www.youtube.com/embed/FVPGJHinItI"},
                {titre:"Hello World App",url:"https://www.youtube.com/embed/mDoHtD1hI3I"},
                {titre:"Components",url:"https://www.youtube.com/embed/16rQyEQtpyQ"},
                {titre:"Interpolation",url:"https://www.youtube.com/embed/2a6OfacW_-I"},
                {titre:"Property Binding",url:"https://www.youtube.com/embed/N8FBmB2jme8"},
                {titre:"Class Binding",url:"https://www.youtube.com/embed/Y6OP-lPJxgs"},
                {titre:"Style Binding",url:"https://www.youtube.com/embed/q256X6-u9Q8"},
                {titre:"Event Binding",url:"https://www.youtube.com/embed/ZfIc1_oj7uM"},
                {titre:"Template Reference Variables",url:"https://www.youtube.com/embed/Oo0-r_YhoJs"},
                {titre:"Two Way Binding",url:"https://www.youtube.com/embed/DOWwWsbG1Sw"},
                {titre:"ngIf Directive",url:"https://www.youtube.com/embed/nWst87nQmZQ"},
                {titre:"ngSwitch Directive",url:"https://www.youtube.com/embed/WiDn2y1Ktws"},
                {titre:"ngFor Directive",url:"https://www.youtube.com/embed/Du3p6QYGs3A"},
                {titre:"Component Interaction",url:"https://www.youtube.com/embed/BGy8DdGw_WE"},
                {titre:"Pipes",url:"https://www.youtube.com/embed/y8lwG8IM82k"},
                {titre:"Services",url:"https://www.youtube.com/embed/pwuGBvOPFYI"},
                {titre:"Dependency Injection",url:"https://www.youtube.com/embed/OFPIGlxunL0"},
                {titre:"Using a Service",url:"https://www.youtube.com/embed/69VeYoKzL6I"},
                {titre:"HTTP and Observables",url:"https://www.youtube.com/embed/vj0kUzKOgGQ"},
                {titre:"Fetch Data Using HTTP",url:"https://www.youtube.com/embed/LmIsbzt-S_E"},
                {titre:"HTTP Error Handling",url:"https://www.youtube.com/embed/TmTGQiLBS5A"},
                {titre:"Routing and Navigation",url:"https://www.youtube.com/embed/Nehk4tBxD4o"},
                {titre:"Wildcard Route and Redirecting Routes",url:"https://www.youtube.com/embed/QC6wRxXT26I"},
                {titre:"Route Parameters",url:"https://www.youtube.com/embed/qh5nHv-4aw0"},
                {titre:"paramMap Observable",url:"https://www.youtube.com/embed/KRV9jZwl0Ig"},
                {titre:"Optional Route Parameters",url:"https://www.youtube.com/embed/gnTFkl2AF-w"},
                {titre:"Relative Navigation",url:"https://www.youtube.com/embed/qktmk-7Kot8"},
                {titre:"Child Routes",url:"https://www.youtube.com/embed/ZoeZxpfTCXk"},
                {titre:"Angular 6 New Features and Changes",url:"https://www.youtube.com/embed/RkV_LozGP3w"},
                {titre:"Updating your app to angular 6",url:"https://www.youtube.com/embed/ScaKGrW5s0I"}
            ],
            [
                {titre:"Introduction",url:"https://www.youtube.com/embed/DwTNR3EBSJQ"},
                {titre:"Installing the Angular CLI",url:"https://www.youtube.com/embed/5OLLPQq1GqQ"},
                {titre:"Intro to TypeScript",url:"https://www.youtube.com/embed/Gn8FEdVtM18"},
                {titre:"Core Files Overview",url:"https://www.youtube.com/embed/PXkXR26U04g"},
                {titre:"Components",url:"https://www.youtube.com/embed/YKi2A2PFTnc"},
                {titre:"Templates & CSS",url:"https://www.youtube.com/embed/A90UT3o5bMk"},
                {titre:"Creating a Component",url:"https://www.youtube.com/embed/GMkF1iUY3n8"},
                {titre:"Nesting Components",url:"https://www.youtube.com/embed/uQZDNTeR44E"},
                {titre:"Ng-Content Directive",url:"https://www.youtube.com/embed/7RQDIChgaZk"},
                {titre:"Data Binding",url:"https://www.youtube.com/embed/VF47uWWql04"},
                {titre:"Property Binding",url:"https://www.youtube.com/embed/VkxyuKuJZrM"},
                {titre:"Event Binding",url:"https://www.youtube.com/embed/uh5ZKGEEAkY"},
                {titre:"2 Way Data Binding",url:"https://www.youtube.com/embed/HXjVelFtpuQ"},
                {titre:"Custom Property Binding (& @Input)",url:"https://www.youtube.com/embed/qenFRHDxU6E"},
                {titre:"Custom Event Binding (& @Output)",url:"https://www.youtube.com/embed/xFYzfHGCJBw"},
                {titre:"Routing",url:"https://www.youtube.com/embed/patjvNM9Qbc"},
                {titre:"Adding Links",url:"https://www.youtube.com/embed/NPCdCknF6TY"},
                {titre:"Route Params",url:"https://www.youtube.com/embed/8KPPRzRLvjc"},
                {titre:"Directives Introduction",url:"https://www.youtube.com/embed/Wwix0JSQKF8"},
                {titre:"ngFor",url:"https://www.youtube.com/embed/GqTJy9VALhI"},
                {titre:"Pipes",url:"https://www.youtube.com/embed/iCmV2jBdDS8"},
                {titre:"Custom Filter Pipe",url:"https://www.youtube.com/embed/sVTNaYBVP88"},
                {titre:"Services",url:"https://www.youtube.com/embed/74NARvL2BI0"},
                {titre:"HTTP Service",url:"https://www.youtube.com/embed/IOp9OmNdHy4"},
                {titre:"Connecting to Firebase",url:"https://www.youtube.com/embed/H9HZ41vM7mk"},
                {titre:"Firebase API",url:"https://www.youtube.com/embed/Fb9o2uwRAk0"},
                {titre:"Posting Data to Firebase",url:"https://www.youtube.com/embed/YEizFZ6eaas"}
            ],
            [
                {titre:"What is a REST API?",url:"https://www.youtube.com/embed/BRdcRFvuqsE"},
                {titre:"Setting up Node.js",url:"https://www.youtube.com/embed/A5fiWcVcADw"},
                {titre:"HTTP Methods",url:"https://www.youtube.com/embed/Fizxr21bjWU"},
                {titre:"Creating an Express App",url:"https://www.youtube.com/embed/7uXKyRFTlWA"},
                {titre:"Handling Requests",url:"https://www.youtube.com/embed/Bc2QE-kHbu0"},
                {titre:"Creating Routes",url:"https://www.youtube.com/embed/BNikS1X5NVk"},
                {titre:"Postman",url:"https://www.youtube.com/embed/3Nvx0mNXPc4"},
                {titre:"Handling POST Requests (& middleware)",url:"https://www.youtube.com/embed/bWiW7tLtlJM"},
                {titre:"Models & Schemas",url:"https://www.youtube.com/embed/aoB0IkQ_1jE"},
                {titre:"Saving Data to MongoDB",url:"https://www.youtube.com/embed/cOt8LfcA9wY"},
                {titre:"Error Handling",url:"https://www.youtube.com/embed/w1V2SdzdQBs"},
                {titre:"Handling DELETE Requests",url:"https://www.youtube.com/embed/NEFfbK323Ok"},
                {titre:"PUT Requests",url:"https://www.youtube.com/embed/sEkRmVfc8XE"},
                {titre:"GeoJSON",url:"https://www.youtube.com/embed/MvY8vcrojYw"},
                {titre:"GET Requests",url:"https://www.youtube.com/embed/k8mi38BI55g"},
                {titre:"Creating a Front-end",url:"https://www.youtube.com/embed/fGQFeV32nwE"},
                {titre:"Creating a React Component",url:"https://www.youtube.com/embed/f7zXuZRsCTk"},
            ]
      ];
}
