/*
* Program : fonction youtubeEmbedUrls qui retourne un tableau de tutoriel youtube
* Écrit par : Dan Duc Dao
*/

export default function youtubeEmbedUrls(){
      return [
                [
                    {titre : "Introduction",url :"https://www.youtube.com/embed/5LYrN_cAJoA"},
                    {titre:"The Vue Instance",url:"https://www.youtube.com/embed/3ROjxrSa5pk"},
                    {titre:"Data & Methods",url:"https://www.youtube.com/embed/2MAoq2-2nnE"},
                    {titre:"Data Binding",url:"https://www.youtube.com/embed/xIOwFTCBBDg"},
                    {titre:"Events",url:"https://www.youtube.com/embed/DCwOPBxsXDs"},
                    {titre:"Event Modifiers",url:"https://www.youtube.com/embed/VqKjr4I4Fdo"},
                    {titre:"Keyboard Events",url:"https://www.youtube.com/embed/Ni6qd0uRoKY"},
                    {titre:"Two-Way Data Binding",url:"https://www.youtube.com/embed/FgvjjYBP2A0"},
                    {titre:"Computed Properties",url:"https://www.youtube.com/embed/O14qJr5sKXo"},
                    {titre:"Dynamic CSS Classes",url:"https://www.youtube.com/embed/4Gh5YcvGDjI"},
                    {titre:"Conditionals",url:"https://www.youtube.com/embed/0EJqZLcwVLY"},
                    {titre:"Looping with v-for",url:"https://www.youtube.com/embed/9Hcswbo0nCY"},
                    {titre:"Simple Punchbag Game",url:"https://www.youtube.com/embed/WjfpQlVem-8"},
                    {titre:"Multiple Vue Instances",url:"https://www.youtube.com/embed/k5p3TozQt84"},
                    {titre:"Intro to Components",url:"https://www.youtube.com/embed/EAONyIKrZN0"},
                    {titre:"Refs",url:"https://www.youtube.com/embed/rSyFM2FANtk"},
                    {titre:"The Vue CLI",url:"https://www.youtube.com/embed/MBZVDsB4VMA"},
                    {titre:"Vue Files & The Root Component",url:"https://www.youtube.com/embed/yP5Tu3S_FtU"},
                    {titre:"Nesting Components",url:"https://www.youtube.com/embed/ko5Eijiaozo"},
                    {titre:"Component CSS (scoped)",url:"https://www.youtube.com/embed/LsoLfELhG74"},
                    {titre:"Nesting Components Examples",url:"https://www.youtube.com/embed/6-us2D7GQCk"},
                    {titre:"Props",url:"https://www.youtube.com/embed/9qqFH60isFc"},
                    {titre:"Primitive vs Reference Types",url:"https://www.youtube.com/embed/gfT0udzYkyw"},
                    {titre:"Events (child to parent)",url:"https://www.youtube.com/embed/5pvG6fzkdFM"},
                    {titre:"The Event Bus",url:"https://www.youtube.com/embed/jzh4zQcfB0o"},
                    {titre:"Life-cycle Hooks",url:"https://www.youtube.com/embed/8rn3SK4N8Go"},
                    {titre:"Slots",url:"https://www.youtube.com/embed/F44OoFk8spg"},
                    {titre:"Dynamic Components",url:"https://www.youtube.com/embed/09n2945JW_0"},
                    {titre:"Input Binding (Creating a blog, part 1)",url:"https://www.youtube.com/embed/yopDG8t60ko"},
                    {titre:"Checkbox Binding",url:"https://www.youtube.com/embed/IkymKuIkajE"},
                    {titre:"Select Box Binding",url:"https://www.youtube.com/embed/xtmZVV9QpaA"},
                    {titre:"HTTP Requests",url:"https://www.youtube.com/embed/btDfVBPYI-U"},
                    {titre:"GET Requests",url:"https://www.youtube.com/embed/aoWqFLGCK60"},
                    {titre:"Custom Directives",url:"https://www.youtube.com/embed/3-fLYMEKOU0"},
                    {titre:"Filters",url:"https://www.youtube.com/embed/o8UspKnsV_0"},
                    {titre:"Custom Search Filter",url:"https://www.youtube.com/embed/G34_yNV8FMY"},
                    {titre:"Registering Things Locally",url:"https://www.youtube.com/embed/T5h6L5MFLRA"},
                    {titre:"Mixins",url:"https://www.youtube.com/embed/YZuml1Y9BmQ"},
                    {titre:"Setting up Routing",url:"https://www.youtube.com/embed/Zflo2-s4768"},
                    {titre:"Hash vs History (Routing)",url:"https://www.youtube.com/embed/js5Sr_ZSHDs"},
                    {titre:"Adding Router Links",url:"https://www.youtube.com/embed/yn0_6T4HwHs"},
                    {titre:"Route Parameters",url:"https://www.youtube.com/embed/KGFcgnCSS6A"},
                    {titre:"Posting to Firebase",url:"https://www.youtube.com/embed/CzJyGo5rh7M"},
                    {titre:"Retrieving Posts from Firebase",url:"https://www.youtube.com/embed/ieCsEdq94TA"}
                ],
                [
                    {titre:"Course plan and prerequisites",url:"https://www.youtube.com/embed/YPShu0H3RbM"},
                    {titre:"Examining some problems with JavaScript",url:"https://www.youtube.com/embed/BaCWKZr-lEE"},
                    {titre:"How TypeScript works",url:"https://www.youtube.com/embed/g486mWGk8VM"},
                    {titre:"TypeScript versus JavaScript",url:"https://www.youtube.com/embed/JAT0xC-5_Jk"},
                    {titre:"Setting up TypeScript",url:"https://www.youtube.com/embed/F7dq4Ec02A0"},
                    {titre:"Introducing type declarations",url:"https://www.youtube.com/embed/oinvkh5B05E"},
                    {titre:"Arrays and tuples",url:"https://www.youtube.com/embed/yYblYVQKn2U"},
                    {titre:"Type erasure and error behavior",url:"https://www.youtube.com/embed/lxcywrPzCGI"},
                    {titre:"Typing with functions",url:"https://www.youtube.com/embed/do_8hnj45zg"},
                    {titre:"Implicit typing",url:"https://www.youtube.com/embed/leErA89nzB8"},
                    {titre:"Any and union types",url:"https://www.youtube.com/embed/bDxVddA1Y-k"},
                    {titre:"TypeScript classes",url:"https://www.youtube.com/embed/B_lYZ715ja4"},
                    {titre:"Methods and constructors",url:"https://www.youtube.com/embed/d9IJyMOmJoE"},
                    {titre:"Inheritance and Polymorphism In TypeScript",url:"https://www.youtube.com/embed/Sn6K57YSuwU"},
                    {titre:"Interfaces and Duck Typing",url:"https://www.youtube.com/embed/v1ShOuVKikM"},
                    {titre:"Member visibility",url:"https://www.youtube.com/embed/_rVFmuX8wMU"},
                    {titre:"readonly modifier",url:"https://www.youtube.com/embed/cYBDtNnjmlA"},
                    {titre:"Enums",url:"https://www.youtube.com/embed/tkPzU-pYErk"},
                    {titre:"Generics",url:"https://www.youtube.com/embed/VPuk5gDXzoo"},
                    {titre:"Modules",url:"https://www.youtube.com/embed/BqZvveICURk"},
                    {titre:"TypeScript compiler arguments",url:"https://www.youtube.com/embed/iIVIv1izd8k"},
                    {titre:"Using tsconfig json file",url:"https://www.youtube.com/embed/JwFaSxCS-2g"},
                    {titre:"Creating an npm project",url:"https://www.youtube.com/embed/90b9MgQvwUY"},
                    {titre:"Installing libraries and type definitions",url:"https://www.youtube.com/embed/HRrGr0FIPAg"},
                    {titre:"Setting up the project",url:"https://www.youtube.com/embed/F_wlRz-tpZ4"},
                    {titre:"Installing dependencies",url:"https://www.youtube.com/embed/5A_u1g7Z-hc"},
                    {titre:"Creating model classes",url:"https://www.youtube.com/embed/Mps99WoVcWI"},
                    {titre:"Creating an api request service",url:"https://www.youtube.com/embed/0OL8DlbGYQg"},
                    {titre:"Calling service and troubleshooting errors",url:"https://www.youtube.com/embed/5hqzQKaHgj8"},
                    {titre:"Convert response to model object",url:"https://www.youtube.com/embed/zCdjVGqc3gk"},
                    {titre:"Using callbacks and handling repo response",url:"https://www.youtube.com/embed/7E9U3XxHU2Y"},
                    {titre:"Chaining calls and accepting commandline argument",url:"https://www.youtube.com/embed/XfEtSYujbpk"},
                    {titre:"Conclusion",url:"https://www.youtube.com/embed/6Km-4HkYkbA"}
                ],
                [
                    {titre:"Introduction",url:"https://www.youtube.com/embed/w-7RQ46RgxU"},
                    {titre:"Installing Node JS",url:"https://www.youtube.com/embed/1US-P13yKVs"},
                    {titre:"The V8 Engine",url:"https://www.youtube.com/embed/86tgU7UaJmU"},
                    {titre:"The Global Object",url:"https://www.youtube.com/embed/PY-AycMkEAg"},
                    {titre:"Function Expressions",url:"https://www.youtube.com/embed/lK42xIMcA0Y"},
                    {titre:"Modules and require",url:"https://www.youtube.com/embed/xHLd36QoS4k"},
                    {titre:"Module Patterns",url:"https://www.youtube.com/embed/9UaZtgB5tQI"},
                    {titre:"The Node Event Emitter",url:"https://www.youtube.com/embed/NtrnaTKqFPQ"},
                    {titre:"Reading & Writing Files (fs)",url:"https://www.youtube.com/embed/U57kU311-nE"},
                    {titre:"Creating & Removing Directories",url:"https://www.youtube.com/embed/Ejgd-la6nSY"},
                    {titre:"Clients & Servers",url:"https://www.youtube.com/embed/qSAze9b0wrY"},
                    {titre:"Creating a Server",url:"https://www.youtube.com/embed/lm86czWdrk0"},
                    {titre:"Streams and Buffers",url:"https://www.youtube.com/embed/GlybFFMXXmQ"},
                    {titre:"Readable Streams",url:"https://www.youtube.com/embed/E3tTzx0Qoj0"},
                    {titre:"Writable Streams",url:"https://www.youtube.com/embed/DvlCT0N7yQI"},
                    {titre:"Pipes",url:"https://www.youtube.com/embed/a8W90jDHSho"},
                    {titre:"Serving HTML Pages",url:"https://www.youtube.com/embed/BBOUfdUZIVo"},
                    {titre:"Serving JSON Data",url:"https://www.youtube.com/embed/QxjVZFa1XUM"},
                    {titre:"Basic Routing",url:"https://www.youtube.com/embed/_zvWeGwVkCY"},
                    {titre:"The Node Package Manager",url:"https://www.youtube.com/embed/kQ1j0rEI7EI"},
                    {titre:"The package.json File",url:"https://www.youtube.com/embed/_eRwjuIDJ2Y"},
                    {titre:"Installing Nodemon",url:"https://www.youtube.com/embed/4N0d8HhU5DE"},
                    {titre:"Introduction to Express",url:"https://www.youtube.com/embed/9TSBKO59u0Y"},
                    {titre:"Express Route Params",url:"https://www.youtube.com/embed/MuMs1pLuT7I"},
                    {titre:"Template Engines",url:"https://www.youtube.com/embed/oZGmHNZv7Sc"},
                    {titre:"Template Engines ( part 2 )",url:"https://www.youtube.com/embed/RczQp3zCPXs"},
                    {titre:"Partial Templates",url:"https://www.youtube.com/embed/CdvSVkF9m_Y"},
                    {titre:"Middleware & Static Files",url:"https://www.youtube.com/embed/-lRgL9kj_h0"},
                    {titre:"Query Strings",url:"https://www.youtube.com/embed/QTAYRmMsVCI"},
                    {titre:"Handling POST Requests",url:"https://www.youtube.com/embed/rin7gb9kdpk"},
                    {titre:"Making a To-do App (part 1)",url:"https://www.youtube.com/embed/edOmvng5IQc"},
                    {titre:"Making a To-do App (part 2)",url:"https://www.youtube.com/embed/nleI7IbpGhc"},
                    {titre:"Making a To-do App (part 3)",url:"https://www.youtube.com/embed/NA21dUBfJhw"},
                    {titre:"Making a To-do App (part 4)",url:"https://www.youtube.com/embed/IgAH0NqsJso"},
                    {titre:"Intro to NoSQL / MongoDB",url:"https://www.youtube.com/embed/L4OP8JGKbQU"},
                    {titre:"Making a To-do App (part 5)",url:"https://www.youtube.com/embed/yevfxvt5r7Y"},
                    {titre:"Making a To-do App (part 6)",url:"https://www.youtube.com/embed/yox93sB2PyQ"}
                ],
                [
                    {titre:"Why Learn Python?",url:"https://www.youtube.com/embed/Ozrduu2W9B8"},
                    {titre:"Installing Python 3",url:"https://www.youtube.com/embed/SbQAAuom-GA"},
                    {titre:"Numbers",url:"https://www.youtube.com/embed/Gqby4v5JOu4"},
                    {titre:"Strings",url:"https://www.youtube.com/embed/---_iWTjtB4"},
                    {titre:"Lists",url:"https://www.youtube.com/embed/cl0R4Tbf2v0"},
                    {titre:"Standard Input",url:"https://www.youtube.com/embed/CEO614YbQCY"},
                    {titre:"String Formatting",url:"https://www.youtube.com/embed/yVGSeRcQfyI"},
                    {titre:"If Statements",url:"https://www.youtube.com/embed/t3c41sKJS20"},
                    {titre:"For Loops",url:"https://www.youtube.com/embed/ENMCxQ9kNS4"},
                    {titre:"While Loops",url:"https://www.youtube.com/embed/7p-BJ92aZp0"},
                    {titre:"Ranges",url:"https://www.youtube.com/embed/GhrChSfaiu0"},
                    {titre:"Functions",url:"https://www.youtube.com/embed/l0E1tK-O8ew"},
                    {titre:"Variable Scope",url:"https://www.youtube.com/embed/wueXfiVkw1I"},
                    {titre:"Dictionaries",url:"https://www.youtube.com/embed/q8H5R6eP3zQ"},
                    {titre:"Sorting & Sets",url:"https://www.youtube.com/embed/UirJNoJ9KT8"},
                    {titre:"Classes",url:"https://www.youtube.com/embed/H--VDcDSHdg"},
                    {titre:"The init function",url:"https://www.youtube.com/embed/TO1K8_BVCT4"},
                    {titre:"Methods & Attributes",url:"https://www.youtube.com/embed/LwFnF9XoEfM"},
                    {titre:"Modules & Packages",url:"https://www.youtube.com/embed/f26nAmfJggw"},
                    {titre:"Bar Tab Calculator",url:"https://www.youtube.com/embed/h4NetyxAhv4"},
                    {titre:"List Comprehensions",url:"https://www.youtube.com/embed/7G0jqG_kiig"},
                    {titre:"Maps",url:"https://www.youtube.com/embed/3Da00hgQ834"},
                    {titre:"Filters",url:"https://www.youtube.com/embed/jPoY--eTG5A"},
                    {titre:"Lambdas",url:"https://www.youtube.com/embed/3waZGETmzjY"},
                    {titre:"Decorators",url:"https://www.youtube.com/embed/mmiIjmo-GwQ"},
                    {titre:"Reading Files",url:"https://www.youtube.com/embed/EPHK0X3yxLs"},
                    {titre:"Reading Files",url:"https://www.youtube.com/embed/EPHK0X3yxLs"},
                    {titre:"Writing Files",url:"https://www.youtube.com/embed/cVUhE0-NUzs"},
                    {titre:"Themed Lorem Ipsum Generator",url:"https://www.youtube.com/embed/iLS4Hk-kJXE"},
                    {titre:"Downloading Images",url:"https://www.youtube.com/embed/2Rf01wfbQLk"}
                ],
                [
                    {titre:"Classes and Instances",url:"https://www.youtube.com/embed/ZDa-Z5JzLYM"},
                    {titre:"Class Variables",url:"https://www.youtube.com/embed/BJ-VvGyQxho"},
                    {titre:"classmethods and staticmethods",url:"https://www.youtube.com/embed/rq8cL2XMM5M"},
                    {titre:"Inheritance - Creating Subclasses",url:"https://www.youtube.com/embed/RSl87lqOXDE"},
                    {titre:"Special (Magic/Dunder) Methods",url:"https://www.youtube.com/embed/3ohzBxoFHAY"},
                    {titre:"Property Decorators - Getters, Setters, and Deleters",url:"https://www.youtube.com/embed/jCzT9XFZ5bw"},
                ],
                [
                    {titre:"Introduction",url:"https://www.youtube.com/embed/pIG1A7UdozM"},
                    {titre:"XAMPP PHP7 setup",url:"https://www.youtube.com/embed/yWCo5Iae9ak"},
                    {titre:"Primitive type declarations",url:"https://www.youtube.com/embed/3RtYLZaUUdU"},
                    {titre:"Object type declarations",url:"https://www.youtube.com/embed/Ms_O8GdmuTw"},
                    {titre:"Return type declarations",url:"https://www.youtube.com/embed/P1tinI0HJr0"},
                    {titre:"Null coalescing operator",url:"https://www.youtube.com/embed/gS-Ym5dRmUI"},
                    {titre:"Spaceship operator",url:"https://www.youtube.com/embed/XYfHeQRm6UA"},
                    {titre:"Constant arrays using define",url:"https://www.youtube.com/embed/sL7espPTVvM"},
                    {titre:"Anonymous classes",url:"https://www.youtube.com/embed/__S6cs4sKAE"},
                    {titre:"Unicode codepoint escape syntax",url:"https://www.youtube.com/embed/IlE9hAQ73ok"},
                    {titre:"Functional call context",url:"https://www.youtube.com/embed/VuS_xLa_Tjo"},
                    {titre:"Unserialize filtering",url:"https://www.youtube.com/embed/U1TdOtYHWVk"},
                    {titre:"Expectations",url:"https://www.youtube.com/embed/FjLA8nnwuwM"},
                    {titre:"Namespacing, use and group use declarations in PHP",url:"https://www.youtube.com/embed/V0CtmYaSju8"},
                    {titre:"Integer division",url:"https://www.youtube.com/embed/iVDFCTmXJmA"},
                    {titre:"Session options",url:"https://www.youtube.com/embed/b66pbZe512U"},
                    {titre:"Random bytes and random int functions",url:"https://www.youtube.com/embed/KAS4yZGHR_4"},
                    {titre:"Revamped regular expression function",url:"https://www.youtube.com/embed/BILQ1FBGDSw"},
                    {titre:"What are Generators?",url:"https://www.youtube.com/embed/AtoIOT18-mw"},
                    {titre:"Generator Syntax",url:"https://www.youtube.com/embed/2a-d2lcIcn8"},
                    {titre:"Generator Yielding Values",url:"https://www.youtube.com/embed/RGABOv-MgdU"},
                    {titre:"PHP7 Generator new features",url:"https://www.youtube.com/embed/A81TAMMb3sk"},
                    {titre:"Deprecated features of PHP7",url:"https://www.youtube.com/embed/sioobwq0TAk"},
                    {titre:"Conclusion",url:"https://www.youtube.com/embed/ju13ePdnqNM"},
                ],
                [
                    {titre:"Install and Setup for Mac and Windows",url:"https://www.youtube.com/embed/YYXdXT2l-Gg"},
                    {titre:"Strings - Working with Textual Data",url:"https://www.youtube.com/embed/k9TUPpGqYTo"},
                    {titre:"Integers and Floats - Working with Numeric Data",url:"https://www.youtube.com/embed/khKv-8q7YmY"},
                    {titre:"Lists, Tuples, and Sets",url:"https://www.youtube.com/embed/W8KRzm-HUcc"},
                    {titre:"Dictionaries - Working with Key-Value Pairs",url:"https://www.youtube.com/embed/daefaLgNkw0"},
                    {titre:"Conditionals and Booleans - If, Else, and Elif Statements",url:"https://www.youtube.com/embed/DZwmZ8Usvnk"},
                    {titre:"Loops and Iterations - For/While Loops",url:"https://www.youtube.com/embed/6iF8Xb7Z3wQ"},
                    {titre:"Functions",url:"https://www.youtube.com/embed/9Os0o3wzS_I"},
                    {titre:"Functions",url:"https://www.youtube.com/embed/9Os0o3wzS_I"},
                ]
             ];
};
